from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from Auth.schemas.schemas import UsuarioLogin
from database.config import get_db
from database.models.user_model import Usuario
from Auth.utils.password_utils import verify_password
from Auth.utils.jwt_utils import crear_token
from database.models.encuesta_model import RespuestaEncuestaDB  # ðŸ‘ˆ AsegÃºrate que esto es correcto

router = APIRouter()

@router.post("/login")
def login(usuario: UsuarioLogin, db: Session = Depends(get_db)):
    db_usuario = db.query(Usuario).filter(Usuario.email == usuario.email).first()
    if not db_usuario or not verify_password(usuario.password, db_usuario.hashed_password):
        raise HTTPException(status_code=401, detail="Credenciales incorrectas")

    token = crear_token({"sub": db_usuario.email, "id": db_usuario.id})

    # ðŸ‘‡ Comprobar si respondiÃ³ la encuesta
    respuesta = db.query(RespuestaEncuestaDB).filter(RespuestaEncuestaDB.usuario_id == db_usuario.id).first()
    encuesta_completada = respuesta is not None

    return {
        "id": db_usuario.id,
        "email": db_usuario.email,
        "nombre": db_usuario.nombre,
        "token": token,
        "encuesta_completada": encuesta_completada
    }
